import { useState } from "react";
import { Eye, EyeOff, LoaderCircle, LockKeyhole, Mail, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Checkbox } from "@/components/ui/checkbox";
import { Label } from "@/components/ui/label";
import logo from "@/assets/tiziflow-logo.png";
import hero from "@/assets/hero-main.png";
import { Environment } from "./Environment";

export function Login({onLogin}:{onLogin:(remember:boolean)=>void}){const[email,setEmail]=useState("admin@tiziflow.ma");const[password,setPassword]=useState("Admin123!");const[show,setShow]=useState(false);const[remember,setRemember]=useState(true);const[loading,setLoading]=useState(false);const[error,setError]=useState("");
 const submit=(e:React.FormEvent)=>{e.preventDefault();setError("");if(email!=="admin@tiziflow.ma"||password!=="Admin123!"){setError("Identifiants incorrects. Vérifiez l’adresse et le mot de passe.");return}setLoading(true);window.setTimeout(()=>onLogin(remember),850)};
 return <main className="login-page" style={{backgroundImage:`url(${hero})`}}><Environment/><div className="login-shade"/><section className="login-intro"><span className="eyebrow light">MIDELT · ATLAS MAROCAIN</span><h1>Mission Control<br/><em>des aventures électriques.</em></h1><p>Supervisez chaque départ, chaque moto et chaque expérience depuis un espace opérationnel unique.</p><div className="mission-status"><span/><b>Systèmes opérationnels</b><small>12 motos · 3 excursions actives</small></div></section><form className="login-card" onSubmit={submit}><header><img src={logo} alt="TiziFlow"/><div><span>BACK-OFFICE</span><p>Centre des opérations</p></div></header><div className="secure-label"><ShieldCheck/> Accès sécurisé · équipe TiziFlow</div><div className="field"><Label htmlFor="email">Adresse e-mail</Label><div><Mail/><Input id="email" type="email" value={email} onChange={e=>setEmail(e.target.value)} required maxLength={255}/></div></div><div className="field"><Label htmlFor="password">Mot de passe</Label><div><LockKeyhole/><Input id="password" type={show?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} required minLength={8} maxLength={100}/><button type="button" className="field-icon" aria-label={show?"Masquer le mot de passe":"Afficher le mot de passe"} onClick={()=>setShow(v=>!v)}>{show?<EyeOff/>:<Eye/>}</button></div></div><div className="login-options"><Label><Checkbox checked={remember} onCheckedChange={v=>setRemember(v===true)}/> Se souvenir de moi</Label><button type="button" onClick={()=>setError("Contactez l’administrateur TiziFlow pour réinitialiser votre accès.")}>Mot de passe oublié ?</button></div>{error&&<p className="login-error">{error}</p>}<Button type="submit" size="lg" disabled={loading} className="w-full">{loading?<><LoaderCircle className="animate-spin"/>Connexion sécurisée…</>:<>Entrer dans Mission Control <span>→</span></>}</Button><footer><span>TF OPS · v2.6</span><span>Fuseau GMT+1 · MAD</span></footer></form></main>}
